primer/behaviors

- package-lock.json
- package.json
- tsconfig.json
After `npm link`ing with PRC, I found a number of tweaks I needed to make.  Also found a bunch of references that needed to be updated before we actually publish this to npm
* Need to set `main` instead of `exports`.  I tried to get fancy with exports so that we could import `@primer/behaviors/utils`, but it didn't work.  For now we can just import `@primer/behaviors/dist/utils` for the one use case we have in PRC.
* The storybook setup in PRC does not do any transpilation on node_modules and was choking on the `??` operators.  I changed the typescript `target` to `es2015` for now so they get transpiled away before we publish
> Update package to work with primer react

- .github/workflows/check_for_changeset.yml
- .github/workflows/release_canary.yml
We don't need to check for changesets on dependabot PRs, and we cannot release a canary version because of permissions issues.
> Ignore dependabot branches for some workflows

- .github/workflows/check_for_changeset.yml
`branches-ignore` is based on _target_ branch for PRs, so we can't use it here
> Skip changeset check for dependabot

- docs/focus-trap.md
The abortController variable is called `dialogController` and incorrectly referenced as `controller` later in the example.
> Fix logic error on docs for focusTrap

- .changeset/eleven-crabs-flow.md
- jest.config.js
- package.json
- tsconfig.json
- utils/package.json
Alternate approach to #39 using `tsc` instead of `babel`. This allows consumers of the package to use either CommonJS or ESM.
> Export both esm and cjs

- .changeset/thirty-gifts-clean.md
- package.json
- utils/package.json
@jaked pointed out that `module` is not officially supported by NodeJS, and is in fact an [optimization used by bundlers like Webpack](https://webpack.js.org/guides/package-exports/#providing-commonjs-and-esm-version-stateless).  We should specify `import` for ESM exports being used by Node.  This change should make it easier to use this package in environments running tests in Node, eg Jest.
> Add `import` conditional export type

- .changeset/rare-donuts-ring.md
- docs/anchored-position.md
- src/__tests__/anchored-position.test.ts
- src/anchored-position.ts
tl;dr: If there isn't enough space  for `align: 'start'`, flip alignment to `align: 'end'` (based on side alternateOrders implementation)
| Before | After |
| ------------- |-------------|
| <img width="298" alt="while in bounds, tooltip is positioned incorrectly" src="https://user-images.githubusercontent.com/1863771/161528230-79eae445-bdd0-4633-963c-76348696199e.png"> | <img width="242" alt="tooltip position is flipped" src="https://user-images.githubusercontent.com/1863771/161528204-bd8c36ad-eda6-4308-ade0-52446a7e3c47.png"> |
- [See tests for more examples](https://github.com/primer/behaviors/pull/78/files#diff-966bd08d7c9fc864ddddfa7cd59d9edfa2440704b1985bf2825253e5a1b5827bR295)
- Fixes: https://github.com/primer/behaviors/issues/63
- Video explanation: …
> Anchored position: Flip to alternative alignments on overflow

- .changeset/gold-forks-march.md
- src/focus-zone.ts
From @jscholes in the [TreeView a11y sign-off](https://github.com/github/primer/issues/1114): 
> On Windows, the Backspace key has an expected function in tree views. It mostly performs the same purpose as Left Arrow, but with an important distinction: it does not collapse nodes.
This PR adds `Backspace` to the list of FocusKeys so we can support the Backspace behavior @jscholes described in TreeView.
> focusZone: Add support for Backspace key

- .changeset/gorgeous-zebras-hammer.md
- src/focus-zone.ts
If a focus zone contains a large number of elements that are added one at a time, performance can suffer. This is because we maintain a list of all focusable elements, and when new elements are added to the focus zone, we do a linear search to find the index of the first currently-managed element that is after the first newly-added element. Since the list is ordered, we can do a binary search instead.
In the repos team's use case (~1000 focusable elements), this change takes us from ~500,000 calls to `compareDocumentPosition` taking a total of about 1000ms, down to ~8,000 calls taking a total of 16ms.
> Use a binary search to find the insertion index for new elements managed by the focus zone

- .changeset/eighty-peaches-smoke.md
- package-lock.json
- src/__tests__/focus-zone.test.tsx
- src/focus-zone.ts
[Slack conversation](https://github.slack.com/archives/C0FSWLQ0Y/p1675807376731229?thread_ts=1675799238.444799&cid=C0FSWLQ0Y)
The first focusable element in a focus zone always has `tabIndex=0` even if a custom `focusInStrategy` function is defined. This sometimes causes NVDA to focus the wrong initial element (see https://github.com/github/primer/issues/1114#issuecomment-1421275869)
If a custom `focusInStrategy` is defined, use it to initialize the tab indexes.
> FocusZone: Use custom focusInStrategy to initialize tabIndex

- .changeset/clean-hornets-greet.md
- src/__tests__/anchored-position.test.ts
- src/anchored-position.ts
When calculating the positioning for an anchored position element, the current algorithm traverses the tree to find "positioned parents"; that is parents with a non-default `overflow` or `position`.
This is acceptable for most elements, but native `<dialog>` and elements with `popover=` get reflected onto the `:top-layer` element, which is adjacent to the document, and therefore layout should be calculated using the main viewport, not any overflow/position parents. 
This PR adds a check to special case such elements, by checking if the element is a `dialog`, or by checking if the `:popover-open` psuedo class is active. Sadly there is no pseudo selector to detect whether or not an element is on the top layer, so we have to check for likely candidates instead.
Fixes …
> special case anchored-position for top-layer elements

- .github/dependabot.yml
Update our `dependabot` config to include support for checking GitHub Actions versions. Also update the config to apply the `dependencies` and `skip changeset` label.
> ci: update dependabot config to include github actions

- .changeset/neat-timers-tease.md
- src/__tests__/focus-trap.test.tsx
- src/__tests__/focus-zone.test.tsx
- src/__tests__/iterate-focusable-elements.test.tsx
- src/focus-zone.ts
- src/utils/iterate-focusable-elements.ts
We ran into a bug when using `useFocusZone` in our component where when the css visibility is set to "hidden" the user is unable to tab past the element. I noticed `iterateFocusableElements` has a `strict` option that checks for elements with hidden visibility but `useFocusZone` does not support the `strict` argument to be passed through to `iterateFocusableElements`. We would like to enable strict mode in `useFocusZone` to remove `visibility: hidden` elements as focusable elements.
More details on the bug: https://github.com/github/issues/issues/7911
Add ability in [focus zone](https://github.com/primer/react/blob/main/src/hooks/useFocusZone.ts#L53) to pass through settings options to `iterateFocusableElements`. Also, I added an additional check to not focus on elements that have …
> Add IterateFocusableElements options to focusZone

- .github/workflows/add-to-inbox.yml
I noticed recently that issues filed in the `primer/behaviors` repo don't end up in our inbox for triage (e.g. https://github.com/orgs/github/projects/4503), so are likely getting missed. 
This PR attempts to create an "add to inbox" workflow for this repo so that new and reopened issues will get labelled as `react` and `rails` (so we can discuss at the appropriate weekly maintainer syncs) and moved into the Inbox of the [Primer teams backlog](https://github.com/orgs/github/projects/4503).
Questions:
- Are all of the `vars`, `steps`, and `secrets` used in this workflow valid? I assumed these values are defined in the specified actions, but would be good to confirm.
- Any other ideas for a better triage plan for `primer/behaviors` issues?
> Create workflow to add primer/behaviors issues to the Primer teams backlog for triage

- .changeset/many-ducks-travel.md
- src/__tests__/iterate-focusable-elements.test.tsx
- src/utils/iterate-focusable-elements.ts
Closes https://github.com/primer/behaviors/issues/236
In the `iterateFocusableElements` method, add support for elements with `contenteditable` HTML attribute to be recognized as focusable elements.
Also, I added some more tests in `iterate-focusable-elements.test.tsx` for `isFocusable` and `isTabbable`
> Add `contenteditable` to iterateFocusableElements

- src/__tests__/anchored-position.test.ts
- src/anchored-position.ts
While debugging https://github.com/github/accessibility-audits/issues/4515 , I was able to narrow down the issue to this criteria.
When zoomed in, the floating element becomes of larger in height compared to the viewport. This results in negative `top` value in the anchor position calculation. Thus results in top parts of the floating element being cut off. 
Before I can try to fix this by messing with the super complex calculations, I thought I'd float a test case to see if my assumptions are right.
I tried to keep the test case values as close to the real life use case as possible. You can see that the height of the floating element is `428px` and the height of the viewport is only `400px`. This already results in a negative `top` value which is buggy as far as I understand.
Open to …
> Position calculation is sus when the floating element is larger than viewport.

- .changeset/chilled-cougars-shout.md
- src/__tests__/anchored-position.test.ts
This commit exists to create a changeset for my previous changes
> Trivial commit

- .github/workflows/release_canary.yml
- .github/workflows/release_candidate.yml
This should have no impact. The dependency is not changed, but this reference is more secure and allows us to modify primer/.github/.github/workflows/release_with_app.yml without breaking consumers code.
> Update release.yml to use tagged dependency

- .changeset/smooth-terms-wait.md
- src/__tests__/focus-zone.test.tsx
- src/focus-zone.ts
- Related to: https://github.com/primer/behaviors/pull/235
- Related to: https://github.com/github/repos/issues/11731
Fix bug found when removing nodes in a focus zone and with strict mode enabled. Also, I added a test to check for this.
We were running into focus inconsistencies when using `useFocusZone` in our component. I pinpointed it to [this line](https://github.com/primer/behaviors/blob/b8a107fbf3d8d10d78490c988a1275fe51f5a010/src/focus-zone.ts#L527) 
```
if (removedNode instanceof HTMLElement) {
endFocusManagement(...iterateFocusableElements(removedNode, iterateFocusableElementsOptions))
}
```
where an empty array was being returned from 
```
iterateFocusableElements(removedNode, iterateFocusableElementsOptions)
```
and the `endFocusManagement` is unable to remove the focusable …
> Remove options when ending focus management

- .changeset/curly-lions-cheat.md
- src/__tests__/focus-trap.test.tsx
- src/focus-trap.ts
Adds a mutation observer to `focus-trap` that ensures that the `sentinel` elements stay at the start/end. The observer only checks for added elements that are direct descendants of the container, meaning that children of those descendants shouldn't trigger the observer.
<hr aria-hidden="true" />
* Added a test to verify that sentinel elements remain at the start and end of the inner container when new elements are added. (`src/__tests__/focus-trap.test.tsx`)
* Added a test to ensure the mutation observer is removed when the focus trap is released. (`src/__tests__/focus-trap.test.tsx`)
* Implemented `observeFocusTrap` function to create a `MutationObserver` that maintains sentinel elements at the correct positions. (`src/focus-trap.ts`)
* Integrated the `observeFocusTrap` function into the …
> Add observer to focus-trap

- .changeset/long-lizards-pump.md
- rollup.config.mjs
- src/__tests__/focus-zone.test.tsx
- src/focus-zone.ts
This PR makes several changes to focus-zone:
1. Passes the abort controller's `signal` to several event listeners where it is currently missing.
2. Changes `clearActiveDescendant` to loop over all child elements with the `data-is-active-descendant` attribute and removes it from each. The current behavior only removes the attribute from a single element, which is a problem in React apps because React re-uses elements with the same key, resulting in more than one element being marked as the active descendant.
> [FocusZone] Clear all active descendants

- .changeset/large-poets-run.md
- src/__tests__/focus-trap.test.tsx
- src/focus-trap.ts
Closes https://github.com/github/primer/issues/3912
Prevent new sentinels from being added if the container already has sentinels. Currently, if you activate a second focus trap, and then deactivate it either manually or on unmount (PRC), it will add duplicate sentinels in the original container. This PR aims to prevent that by checking if the container already has sentinels as direct children.
> Focus-trap: Prevent duplicate sentinels
